language: python

sudo: false

python:
    - "2.6"
    - "2.7"

install:
    - pip install -r requirements.txt
    - pip install coveralls

script:
    coverage run --source=fabricio -m unittest2 discover tests

after_success:
    coveralls

branches:
  only:
    - master
